### ISSUE TITLE
User Story: As an Identify VS and ART workshop participants, I need sufficient SAFe training to meaningfully participate in the event

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#16]
- [x] Review LACE consultants organizing around value material
- [x] Review LACE consultants Identify VS and ART  material
- [x] Identify participants for Organizing Around Value Training

**Comment by jamesmrollins** [comment]
@maneyb1 - Great User Story!!

**Comment by jamesmrollins** [comment]
From 2/23 PM Scrum:

- The LACE consultants will present a "generic" ART workshop.
- Provides more value stream related details, with relationship to our solutions and what we provide to operational value streams (food for thought).
- We will then go to a more refined IHP centric ART workshop that gets down to people assignments and related resource related decisions.  
- Then we will focus on the organizational training plan for preparing people to participate in AGILE teams and the newly organized ART.

**Comment by jamesmrollins** [comment]
## From Thursday 2/23 Planning Meeting

1. User feedback on Wednesday training.
2. Get a clear understanding using examples (using JN examples) of clinical value streams that we can align ourselves. 
3. Define terms:
	- Context
	- Operational Value Stream
	- Process Step
	- Operational Step
4. Identify next workshop participants.
	- Intro to Agile TMS training.
	- Intro to SAFe TMS training
