### ISSUE TITLE
User Story: As a LCMT member, I need all the inputs for a successful workshop prepared

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#18]
- [x] List of people
- [x] Survey participants on questions for identifying operational value streams
- [x] Identify a target  operational value stream
- [x] Identify current agile practices and tools in CIMDO today
- [x] Conduct empathy interviews with workshop participants

**Comment by maneyb1** [comment]
Updated card to make homework more specific to the workshop content.

**Comment by maneyb1** [comment]
Link to pre-workshop exercise: https://forms.office.com/g/Qqgy9X3Bmj

**Comment by jamesmrollins** [comment]
Discuss in 2/23 PM Scrum

@maneyb1 is going to send out the forms cited above to Friday  Workshop Planning Call participants.

- Get a first pass on what they think
- Ask who they think should participate.
- Use food for thought.
- Then we can send the form to the ART Workshop participants identified in the Friday meeting.

**Comment by maneyb1** [comment]
Incorporate V's IHP Lean/OKR efforts into the workshop.
@vvenu0 Invite James and Brenna to meeting with Dr. Cilessen and Jim.

**Comment by maneyb1** [comment]
### State of IHPMB 
IHPMB approval process is stable 
Building teams to execute is not stable 
Out of 6 approved IPTs, cystatin C is the Kate has confidence in delivering 
Cystatin C was approved in November, started to get unstuck in December 
Psychotherapy IPT  Team didn’t' respond to scope of charter and is now paused

**Comment by jamesmrollins** [comment]
Sprint Planning 3/2

- JLV Team is using JIRA and they release in increments.
- The Patient Safety Team uses JIRA for patient safety issue tracking (ticket management).
- FIS - IWS uses Microsoft Planner to plan their workforce development work and HI COP.
- CIDMO Director uses ScrumBan to manage web page development.
- Established a regular meeting with KC and the FIRM to inform about AGILE concepts and answer concerns and gather feedback.  Posting the feedback in related card issues.  
- Met with Jim Weaver regarding the differences between his IPT SOP and the AGILE methods.  Also discussed messaging and the importance of mentally preparing people for the upcoming changes.
