### ISSUE TITLE
Discovery: Identify which dashboards are used at the facility level to assess performance.

### ISSUE THREAD

**Issue by vvenu0** [jamesmrollins/CIDMO_LCMT#19]
- [x] Determine what dashboards and data displays are available which display data and outcomes at the facility level.
- [x] Determine which dashboards and displays could by used by CIDMO.

**Comment by jamesmrollins** [comment]
@vvenu-va will contact @jamesmrollins offline and determine a good time to meet and discuss findings.

**Comment by jamesmrollins** [comment]
@vvenu0 will send out a meeting notice for Thursday.

**Comment by vvenu-va** [comment]
[Performance and Measurement Data Reporting within VHA.docx](https://github.com/jamesmrollins/CIDMO_LCMT/files/8136545/Performance.and.Measurement.Data.Reporting.within.VHA.docx)

**Comment by vvenu-va** [comment]
V is seeking information from the VSSC Help Desk on how we can access some of their customer satisfaction data.

**Comment by jamesmrollins** [comment]
Sprint Planning Meeting 3/2 decisions:

- We are going to pull the Data Dissemination Task off this card and create a new card.
- The new card will go into the Product Backlog.
- Meeting on Thursday to answer what information we want in our dashboard.
