### ISSUE TITLE
User Story: As a LCMT team member, I need a plan to train all staff who will likely participate in first ART

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#21]
- [x] Identify ITWD SAFe schedule and seats available for leading SAFe training, DevSecOps, Portfolio Management, and Product Manager Trainings.
- [x] Skills inventory
- [x] Write a Training Memorandum of Instruction

**Comment by maneyb1** [comment]
- [ ] Identify backlog of students for each class type
- [ ] Decide if we want to invest in training that aligns with our schedule or wait for openings in the ITWD training

Notes on ITWD Classes and Seats available: 
ITWD Fills 10 slots per class 
These classes are free
Participants do need to take the test, regardless if they pass or fail
No influence over schedule 

### SAFe for Teams (traditionally delivered 2 days before ART launch)
Tentatively 5 spots available for CIDMO staff

### SAFe Product Owner/Product Manager
3 classes, should be able to get at least 5 seats 

### ITWD Leading SAFe
Frequent class, Requested 20 seats 

### Contract Training with Tas team for same classes: 
100/person 
Contractors can attend - contractors have to pay separately 
Need to make sure we have way to pay

**Comment by maneyb1** [comment]
James has first draft started, planning to send to Kellie by end of the week. 
There is no memo of instruction template, only a generic memo template

**Comment by maneyb1** [comment]
James will try to finish today and put in QA pipeline. 
Aimee is Brenna's proxy for review before sending to Kellie for signature

**Comment by maneyb1** [comment]
- [ ] Aimee come up with training budget 
- [x] Draft training plan, looking at leading SAFe and SAFe for teams workshops for potential ART members

**Comment by jamesmrollins** [comment]
Hi @aimeebenson @maneyb1 @RossSpeir 

Please find the draft [Training Plan](https://teams.microsoft.com/l/file/77CF59D5-D29C-4913-93BF-67B4A54F007B?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&fileType=docx&objectUrl=https%3A%2F%2Fdvagov.sharepoint.com%2Fsites%2FCopyofMPKanban%2FShared%20Documents%2FLCMT%2FTransformation%20Plan%2FTraining%20Plan%2FCIDMO%20SAFe%20Training%20MOI.docx&baseUrl=https%3A%2F%2Fdvagov.sharepoint.com%2Fsites%2FCopyofMPKanban&serviceName=teams&threadId=19:6f943c3e9d774654812a4599250e56a0@thread.tacv2&groupId=1967f60a-845a-474c-874a-0fd433acaae7). Comments welcome.  I see this MOI as subordinate to the Transformation Plan, which I will author next.

**We need to discuss the training schedule together and determine the timing.**

**Comment by maneyb1** [comment]
Release with the transition plan and the communication plan.

**Comment by brandymorrison** [comment]
@jamesmrollins @aimeebenson I made comments/suggestions in the document for your review. Please let me know if anything additional is needed from me regarding this action.

**Comment by maneyb1** [comment]
@maneyb1 - Review to ensure role-based training is in plan

**Comment by jamesmrollins** [comment]
I am moving the budgeting and scheduling parts of this task to another card.
