### ISSUE TITLE
User Story:  As a CIDMO employee or contractor, I don't have information about upcoming changes and that makes me very anxious.

### ISSUE THREAD

**Issue by jamesmrollins** [jamesmrollins/CIDMO_LCMT#27]
# Prepare Communications Plan

- [x] Target March 8, All employee meeting for substantial explanation and timeline.
- [x] Identify venues to communicate on-going status ( i.e., SharePoint, PowerBI).
- [x] Can we target any other regular meetings for messages?

**Comment by maneyb1** [comment]
Chuck made request to LCMT for update on Tuesday CIDMO Work Effort Meeting.
Brenna asked to defer until at least First week in March. 
Plan forward

- [x] Get JN approval on Lean-Agile and SAFe for all staff scheduled for 3/8
- [x] Bring slides and prepare to answer questions on CIDMO work effort  meeting 3/15

**Comment by maneyb1** [comment]
- [x] Update CIDMO Goes SAFe with calls to action (trainings, link to skillsoft books, case study)

**Comment by brandymorrison** [comment]
Moving this comment to other issue care: ~~Impressions of All Staff: It was a nice platform for introducing the concept to all staff. There was no engagement in the comments from employees. This is only the beginning to the conversation framework being developed. The next crucial step will be engaging with the Coffee, Culture and Conversations team to have a conversation with employees versus briefing them.~~

**Comment by maneyb1** [comment]
@jamesmrollins start a new card for transformation plan ~~- [ ] James will write a transformation plan in response to Jim Weaver's inquiry
Brandy and Aimee will be QA reviewers~~
