### ISSUE TITLE
As a director, I need to understand the ART map and my teams roles within it.

### ISSUE THREAD

**Issue by jamesmrollins** [jamesmrollins/CIDMO_LCMT#28]
# Deliverables

- [x] Will likely follow the ART Workshop.
~~- [ ] Meet with directors for identified value streams and support building teams~~
~~- [ ] Need a migration plan that will prioritize work that people are already performing with the work the ART will be responsible for.~~

**Comment by jamesmrollins** [comment]
# Deliverables

- [x] Will likely follow the ART Workshop.
- [x] Need a migration plan that will prioritize work that people are already performing with the work the ART will be responsible for.

**Comment by maneyb1** [comment]
- [x] Schedule meeting with Elizabeth Griffith to understand how CLIN2 (new name) manages their work.

**Comment by maneyb1** [comment]
@aimeebenson - split tasks beyond first ART into separate issue

**Comment by maneyb1** [comment]
HFE team is meeting this week to determine what they need to achieve. Ross added what success in SAFe looks like. The team is also looking at the national reminder template process. 
@maneyb1 will share ART design after JN approves.

**Comment by maneyb1** [comment]
JN approved initial ART design, meeting with the "the Firm" 3/23 to discuss resourcing the agile teams.

**Comment by maneyb1** [comment]
First ART design approved to be shared with Division management teams to refine and begin discussing resourcing

- [x] Review and update with Kate Cillessen
- [x] Review and update with Jonathan Nebeker
- [x] Review and update with Steve Brown
- [x] Review and update with Darren Wilson
~~- [ ] Review with David Massaro~~
- [x] Review with Tommy Barnes
~~- [ ] Review and update with Jolie Rene~~
- [x] Review and update with Acquisition leads
- [x] Review and update with FIS management staff
- [x] Review and update with HFE management staff
- [x] Review and update with KBS management staff
- [x] Review and update with CLIN 2 team

**Comment by maneyb1** [comment]
Sent Darren and Tommy Barnes a copy of the ART design. Need to follow up to review and discuss. 
@maneyb1 - discuss review with OIT with Kate on Monday

**Comment by maneyb1** [comment]
@maneyb1 
Propose candidate names for teams - see card #54

**Comment by maneyb1** [comment]
Follow-up on Wednesday whether we need to brief ART design to Tommy.

**Comment by jamesmrollins** [comment]
@maneyb1 - Is Tommy the procurement person?

**Comment by maneyb1** [comment]
Jolie took a new position, need to introduce ourselves to  new team
@aimeebenson - schedule meeting with Tommy and team for Monday

**Comment by maneyb1** [comment]
@RossSpeir - please send invite for Monday 11EDT to review IHP ART Design with OIT CPRS team and Kate, and hopefully Jonathan. @jamesmrollins  - confirm with Ross that you can make that time - you will need to drive the review of the map.

**Comment by RossSpeir** [comment]
Kate has requested we postpone this OIT discussion until AFTER next weeks' SAFe training.  I think she's right - the discussion with OIT will be more fruitful when Kate has a better understanding of the new process she oversees.

**Comment by maneyb1** [comment]
Moved partner work to issue #72
