### ISSUE TITLE
As an owner of a CIDMO communication channel, I want approved messaging about SAFe Implementation and Feedback

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#35]

**Comment by maneyb1** [comment]
Draft HRO Lean-Agile Foundations: https://teams.microsoft.com/l/file/D580257F-8EEE-44D1-8F9B-922357ADDEE1?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&fileType=docx&objectUrl=https%3A%2F%2Fdvagov.sharepoint.com%2Fsites%2FCopyofMPKanban%2FShared%20Documents%2FLCMT%2FComms%2FCIDMO%20Lean-Agile%20HRO%20Strategy%20Com%20Campaign.docx&baseUrl=https%3A%2F%2Fdvagov.sharepoint.com%2Fsites%2FCopyofMPKanban&serviceName=teams&threadId=19:6f943c3e9d774654812a4599250e56a0@thread.tacv2&groupId=1967f60a-845a-474c-874a-0fd433acaae7

**Comment by brandymorrison** [comment]
Impressions of All Staff: It was a nice platform for introducing the concept to all staff. There was no engagement in the comments from employees. This is only the beginning to the conversation framework being developed. The next crucial step will be engaging with the Coffee, Culture and Conversations team to have a conversation with employees versus briefing them.

**Comment by maneyb1** [comment]
Impressions of All Staff: It was a nice platform for introducing the concept to all staff. There was no engagement in the comments from employees. This is only the beginning to the conversation framework being developed. The next crucial step will be engaging with the Coffee, Culture and Conversations team to have a conversation with employees versus briefing them.
