### ISSUE TITLE
Enabler: What will be the scope, inputs and outputs, and the target date for the PI Planning Conference

### ISSUE THREAD

**Issue by jamesmrollins** [jamesmrollins/CIDMO_LCMT#40]
# Deliverables
- [x] Engage OIT consultants regarding getting help with the conference. 
- [x] Specify PIPC inputs (required and optional) 
- [x] Specify expected outcomes and next steps after a PIPC 
- [x] Specify the IHP roles participating in a PIPC 
- [x] Identify an opportunity to conduct a PI Planning event for a single clinical value stream 

## Risks
- The PIPC needs to be absolutely successful!! Having some experience with a small, willing team going through the PI Planning process will increase the odds of a successful PI Planning Conference.
- The level of effort needed for a single team may be the same as for 3 teams.

**Comment by maneyb1** [comment]
- [ ] What is outcomes and next steps after PI Planning event
- [x] Memorandum of instruction

**Comment by RossSpeir** [comment]
Discussed the objective to 'Conduct a PI Planning event for a single clinical value stream.'  Per Andrew Keener, a single team's efforts to plan their work (for an Epic, for a quarter), is not considered a 'PI Planning event.'  

I'll rescind my proposal to conduct a 'single-team PI Planning', and will assume that teams participating in the CIDMO PI Planning Conference have KSAs needed to plan and execute work in accordance with SAFe (and the focus on the PIPC is on identifying dependencies, cross-team coordination, etc.).

**Comment by RossSpeir** [comment]
Target dates for PIPC is in May.
MUST have work carried out using SAFe by Q4

**Comment by maneyb1** [comment]
@RossSpeir - we probably need to split this card and move into next sprint. 

@maneyb1 - I agree. SAFE breaks down PI Planning requirements into 3 areas:  Organizational Readiness, Content Readiness, and Logistics Readiness -- we can break out the work this way. We have a much better handle on Organizational Readiness (see notes below), and I think this will be the most difficult to achieve and what we should focus on. 

**Organizational Readiness** 
There must be strategy alignment among participants, stakeholders, and Business Owners. Critical roles are assigned. To address this in advance, however, event organizers must consider the following: 
  • Planning scope and context – Is the scope (product, system, technology domain) of the planning process understood? Do we know which teams need to plan together? 
  • Business alignment – Is there reasonable agreement on priorities among the Business Owners? 
  • Agile teams – Do we have Agile teams? Are there dedicated team members and an identified Scrum Master and Product Owner for each team? 

**Content Readiness**
Ensure that there is a clear vision and context and that the right stakeholders can participate. Therefore, the PI planning must include: 
  • Executive briefing – A briefing that defines the current business context Product vision briefing(s) – 
  • Briefings prepared by Product Management, including the top 10 features in the Program Backlog 
  • Architecture vision briefing – A presentation made by the CTO, Enterprise Architect, or System Architect to communicate new Enablers, features, and Nonfunctional Requirements (NFRs) 

**Logistics Readiness**
Preparing an event to support a large number of attendees isn’t trivial. For physically collocated planning this can include securing and preparing the physical space. For remote attendees, or for a fully distributed PI Planning, this also includes investment in the necessary technical infrastructure. Considerations include: 
  • Locations – Each planning location must be prepared in advance 
  • Technology and tooling – Real-time access to information and tooling to support distributed planning or remote attendees 
  • Communication channels – Primary and secondary audio, video, and presentation channels must be available

**Comment by maneyb1** [comment]
@maneyb1  - update notes from meeting with Andrew

**Comment by RossSpeir** [comment]
We should strive to have our first PIPC in person (and plan to hold future events virtually). We’ll need a [] back-up plan in case an in-person event is not possible. 

We’ll need to [] identify a facility that can accommodate up to 50 people. Options include SLC, SIMLearn center in Orlando. 

@RossSpeir - OIT is not allowed to resume traveling yet so PI planning will likely remain virtual

We need to [] determine the date of the PIPC.  If we could be ready by the week of May 9th, we could have a PIPC as part of the larger agenda that Kellie planning – assuming sufficient time is dedicated to PI Planning. 
@RossSpeir - look at training MOI calendar and see what I am currently proposed

The 'Organizational' inputs (readiness requirements) for a PIPC were provided by Andrew in the ART Readiness Checklist (attached). 

Given the amount of time require to plan and prepare for PI Planning, we need to [] determine preparedness criteria for each ARTs to decide the date and scope of the PIPC.  
@RossSpeir - I think we only have 1 ART this FY....
 
[https://app.zenhub.com/files/454514222/f1b42579-f54f-40af-8eaa-1e30967c6726/download](https://app.zenhub.com/files/454514222/f1b42579-f54f-40af-8eaa-1e30967c6726/download)

**Comment by RossSpeir** [comment]
Our OIT consultants have materials for conducting a 'Simulation for PIP' which is essentially a 3-4 hour single-feature workshop. We need to have this experience (with a CIDMO team) in order to be successful with a multi-feature workshop. I've re-added this requirement to the PIPC plan. 
@RossSpeir - this is the SAFe for Teams and accounted for in the Training plan

**Comment by maneyb1** [comment]
Need to coordinate with Aimee and the Fy222 acquisition work surround 5 identified IHPs.
