### ISSUE TITLE
User Story: As a member of the LCMT, I need to understand how Facilities document their value streams and prioritize improvement issues.

### ISSUE THREAD

**Issue by jamesmrollins** [jamesmrollins/CIDMO_LCMT#43]
## Evaluate VISN 1 Value Stream Maps

- [x] Admission VSM
- [x]  ATD_PFD_CurrentState
- [x] Mammogram
- [x] Outpatient
- [x] Patient Admission

## Evaluate VISN 8 Value Stream Maps

**Comment by jamesmrollins** [comment]
Hi @vvenu-va @maneyb1 

## VISN 1 Value Stream Map Review

- Below is a pretty good VSM artifact from VISN1 regarding admitting and discharge processes. It has measures and relates performance of the activity to SAIL metrics.
- Some of the supporting tabs in the file shown below have supporting workflows, but do not indicate interactions with a technology layer (this would be the linkage to CIDMO and OIT).

![image.png](https://images.zenhubusercontent.com/5e4eac12455ade27f3584cea/3e9d34ea-1ebb-439c-8c55-6d3b80519a8b)

**Comment by maneyb1** [comment]
- [x] @RossSpeir - identify HCD artifacts (journey, persona)
