### ISSUE TITLE
US: As a LCMT member I need to identify candidate development value streams based on current volume of IHP related team work

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#44]
# We Need to Analyze the Flow of Work into The Organization via FIS, HFE and KBSS&I

| Type of Work | Directorate| Requesting Customer | Number of Requests 2020-2021|
|----------------|-------------|------------|------------------------------------|
| Template | FIS|10E1E National Center for Ethics in Health Care| 1 |

## Then Illustrate the Flow Using [Sankey](https://ppcexpo.com/blog/sankey-chart-excel)

**@jamesmrollins can get this chart app on my personal account and process once I have the data.**

![image.png](https://images.zenhubusercontent.com/5e4eac12455ade27f3584cea/68e788c8-8b82-40b4-87bd-23b99d6267e8)

## Need downloads from the following sources

- [x] KBSS&I (@maneyb1 tracking down)
- [x] HFE (@RossSpeir tracking down)
- [x] FIS (NTWC) (@jamesmrollins. tracking down)

**Comment by maneyb1** [comment]
- [x] Export list of template and reminder requests
- [x] Export HFE project Backlog
- [x] Export KBS project backlog
- [x] Create IHP backlog
- [x] Run Pareto analysis
- [x] Meet with Elizabeth Griffith to understand Team capacity and workload management
- [x] Define template value stream

**Comment by maneyb1** [comment]
Link to notes: [https://dvagov.sharepoint.com/sites/CopyofMPKanban/_layouts/15/Doc.aspx?sourcedoc={0984b121-cdf3-4705-9b74-350b46e60e33}&action=edit&wd=target%282.%20VS%20and%20ART%20Identification%2FPrepare%20for%20ART%20ID.one%7Cdee75e7d-37e7-49ef-ad47-8b501a3634e4%2FCGS%20Continue%20to%20discuss%20starting%20point%20for%20SAFe%20-%7C48118491-7d38-4eba-9f13-be868bd049de%2F%29&wdorigin=703](url)

**Comment by maneyb1** [comment]
@jamesmrollins - take how a template becomes national and describe as value stream

**Comment by jamesmrollins** [comment]
@vvenu-va and @jamesmrollins - please meet and discuss data table structure for the pareto analysis
Source files for pareto analysis are in location below. Waiting for KBS and HFE project tracking exports:
https://teams.microsoft.com/_#/files/Identify%20Value%20Streams%20and%20ARTs?threadId=19%3A91df45c15458463fa117fa9a3eb60581%40thread.tacv2&ctx=channel&context=Identify%2520Value%2520Streams%2520and%2520ARTs&rootfolder=%252Fsites%252FCopyofMPKanban%252FShared%2520Documents%252FIdentify%2520Value%2520Streams%2520and%2520ARTs

**Comment by maneyb1** [comment]
@vvenu-va - update the template request with the program office

**Comment by jamesmrollins** [comment]
Hi @vvenu-va - [This r code for Sankey chart](https://plotly.com/r/sankey-diagram/) is what my contact said should give you the necessary information to create a Sankey plot using R code.

**Comment by maneyb1** [comment]
V - 90% done manually linking programs to requests for NCTRs

- [ ] Pull sankey code
- [ ] Analyze data

**Comment by vvenu-va** [comment]
https://app.powerbigov.us/groups/f8385f06-ba47-4655-b2cd-b1b2784f4097/reports/b8d73c9e-5430-4fd5-b324-417e2b0b9d79/ReportSection

**Comment by vvenu-va** [comment]
https://app.powerbigov.us/groups/f8385f06-ba47-4655-b2cd-b1b2784f4097/reports/70b5ab90-e05f-4a1d-9116-e3bf9271fc6c/ReportSection

**Comment by vvenu-va** [comment]
https://app.powerbigov.us/groups/f8385f06-ba47-4655-b2cd-b1b2784f4097/reports/b8d73c9e-5430-4fd5-b324-417e2b0b9d79/ReportSection

**Comment by vvenu-va** [comment]
https://app.powerbigov.us/groups/f8385f06-ba47-4655-b2cd-b1b2784f4097/reports/518c8d3a-92e3-4308-af43-7ff62ae158bc/ReportSection

**Comment by maneyb1** [comment]
- [ ] Validate clean pareto files

**Comment by jamesmrollins** [comment]
As per scrum 3/21:  Close this card and split to #52 .  Also determined that Sankey chart not possible with current data.
