### ISSUE TITLE
As a CIDMO Directorate, I need to understand the situation and what i need to do to support the transformation to Lean-Agile

### ISSUE THREAD

**Issue by jamesmrollins** [jamesmrollins/CIDMO_LCMT#46]
# CIDMO Goes SAFe Transformation Plan

1. Situation:  What in our current situation that necessitates this transformation?
2. Scope:  Who will be affected by this transformation?
3. Purpose: Why are we transforming?
4. Intent: What is the long term vision of how this plan will develop over time?
5. Implementation:  Phase-by-phase description of how CIDMO will transform.
6. Responsibilities: Identify who will do what.
7. Coordination Points: Identifies who gets what, by when.
8. Roadmap:  Graphic description of transformation.
9. Appendices and Supporting Plans: Training Memorandum of Instruction

## Products

- [x] Word document
- [ ] PowerPoint

**Comment by RossSpeir** [comment]
May need to walk through the transition plan with Kelly to get her consensus / buy-in.

**Comment by jamesmrollins** [comment]
Hi @maneyb1 @RossSpeir @davclaBAC @brandymorrison @aimeebenson @vvenu-va please find the [CIDMO Lean-Agile Transformation Plan](https://teams.microsoft.com/l/file/E320057F-3537-4E29-A44B-C95DFFAC6424?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&fileType=docx&objectUrl=https%3A%2F%2Fdvagov.sharepoint.com%2Fsites%2FCopyofMPKanban%2FShared%20Documents%2FLCMT%2FTransformation%20Plan%2FCIDMO%20Transformation%20Plan.docx&baseUrl=https%3A%2F%2Fdvagov.sharepoint.com%2Fsites%2FCopyofMPKanban&serviceName=teams&threadId=19:6f943c3e9d774654812a4599250e56a0@thread.tacv2&groupId=1967f60a-845a-474c-874a-0fd433acaae7) in the Teams repository.

**Comment by jamesmrollins** [comment]
Card split to #49
