### ISSUE TITLE
Communication Plan

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#47]
link campaigns, channels, education and training schedule into unified plan that communicates strategy for SAFe

**Comment by maneyb1** [comment]
Transformation plan is dependent on communications plan, which will communicate larger strategy.

**Comment by maneyb1** [comment]
@brandymorrison - send the overall communications plan, which includes the CIDMO goes SAFe section. Current plan is an excel document that includes channels, audiences, and messages.

**Comment by maneyb1** [comment]
@maneyb1 - do pre-review of comms strategy/plan draft

**Comment by maneyb1** [comment]
Brenna and Kellie did cursory review of structure. 
Brenna will do content review and provide sources for key messages

**Comment by maneyb1** [comment]
@brandymorrison - put all questions in wiki on teams
comms plan will have answers to question the LCMT proactively identifies
@maneyb1  -Do content reviewm package and send to JN for reading material on 3/29 flight

**Comment by maneyb1** [comment]
Didnt get homework to Nebeker in time, as @maneyb1 doing thorough read of all 3 plans. Send to Brandy for final comms review. WIll coordinate time with Kellie to get JN to review/revise.

**Comment by maneyb1** [comment]
@brandymorrison - please do another reconciliation of communications from the core IHP deck, the campaign I started, the All Staff decks, and the Transformation plan

**Comment by brandymorrison** [comment]
@maneyb1 I accepted the communications plan edits, added language in from the all staff presentations and have reviewed the Transformation plan. I did not accept changes, but read as though changes were accepted. I made additional comments in track changes. @jamesmrollins Are you the owner of the Transformation plan to review the track changes?

**Comment by jamesmrollins** [comment]
@maneyb1 @brandymorrison - I am likely owner of the document, but please feel free to accept changes and get the plan out there.  

_We should follow the 1/3 2/3 planning rule, which says that we should give 2/3 planning time to the field and take only 1/3 of the time for ourselves._

:-)

**Comment by maneyb1** [comment]
- [x] Share plan with FIRM
- [x] Share with PMs

**Comment by brandymorrison** [comment]
Will share with all identified PMs after signature

**Comment by aimeebenson** [comment]
I actually already shared with PMs.  :) Told them it was a draft and JN was reviewing.

**Comment by maneyb1** [comment]
This card will be about structuring the plan so that the campaigns match the LCMT roadmap. 
Future cards will be developing campaign specific content
- [ ] look for Gartner resources
