### ISSUE TITLE
Enabler:  Review and Staff Completed Transformation Plan

### ISSUE THREAD

**Issue by jamesmrollins** [jamesmrollins/CIDMO_LCMT#49]
Reference #46

- [ ] Review, edit and publish plan.
- [ ] Complete the Communications plan.
- [ ] Review with relevant stakeholders.
- [ ] Submit to relevant Division and CIDMO Directors.

**Comment by maneyb1** [comment]
Brenna - finish reviewing/editing transformation plan

**Comment by maneyb1** [comment]
@jamesmrollins - review 3/23

**Comment by maneyb1** [comment]
This is pending on comms and training plan

**Comment by maneyb1** [comment]
In addition to the Leading SAFe, I recommend the certification prep: Scrum master for everyone on the ART: https://www.linkedin.com/learning-login/share?account=70115025&forceAccount=false&redirect=https%3A%2F%2Fwww.linkedin.com%2Flearning%2Fcert-prep-scrum-master%3Ftrk%3Dshare_ent_url%26shareId%3DgfxEZN1PTT64CASvjs0qig%253D%253D
