### ISSUE TITLE
User Story:  Continue investigation of KBSS&I Workflows and IHP Integration

### ISSUE THREAD

**Issue by jamesmrollins** [jamesmrollins/CIDMO_LCMT#51]
## Remaining Questions and Analysis:

 - [x] Review Apurva's diagram
 - [x] Validate KBS assertion that IHP is missing a 5th component
 - [x] Get list of BPMN+ models from Ken Ruben
 - [x] Link whiteboard notes with meeting notes

Reference #33

**Comment by maneyb1** [comment]
KBS proposes that content development is a 5th component of IHP. 
See CDS artifact process v3: https://dvagov.sharepoint.com/sites/CopyofMPKanban/_layouts/OneNote.aspx?id=%2Fsites%2FCopyofMPKanban%2FSiteAssets%2FCIDMO%20goes%20SAFe%20Notebook&wd=target%282.%20VS%20and%20ART%20Identification%2FCurrent%20State%2FKBS.one%7C4E823728-111E-443D-8628-E1FB6E8F3AD4%2FRE%3A%20CIDMO%20Goes%20SAFe%3A%20Pre-workshop%20prep%20with%20KBS%7C9948F5C9-F45B-4140-BF7E-77B0C091D949%2F%29
onenote:https://dvagov.sharepoint.com/sites/CopyofMPKanban/SiteAssets/CIDMO%20goes%20SAFe%20Notebook/2.%20VS%20and%20ART%20Identification/Current%20State/KBS.one#RE%20CIDMO%20Goes%20SAFe%20Pre-workshop%20prep%20with%20KBS&section-id={4E823728-111E-443D-8628-E1FB6E8F3AD4}&page-id={9948F5C9-F45B-4140-BF7E-77B0C091D949}&end
