### ISSUE TITLE
User Story: As the LCMT lead, I need to establish the agile teams

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#54]
- [x] Develop Rosters for each team, with roles
- [x] Identify contract resource vs gov resource roles

https://dvagov.sharepoint.com/sites/CopyofMPKanban/_layouts/15/Doc.aspx?OR=teams&action=edit&sourcedoc={1F2CAF6F-E1FB-4D10-B6C9-7CAE1D05E345}

**Comment by aimeebenson** [comment]
- [ ] Meet with directors for identified value streams and support building teams
- [ ] Need a migration plan that will prioritize work that people are already performing with the work the ART will be responsible for.

**Comment by maneyb1** [comment]
@maneyb1 
- [ ] overlay existing projects in ART
- [ ] identify which team will work on which project in PI planning training

**Comment by maneyb1** [comment]
@RossSpeir 
- [ ] Gather feedback from HFE on Team Roster Roles
@aimeebenson 
- [ ] Get feedback from PM community
