### ISSUE TITLE
As the ART RTE, I need to Establish a Program KANBAN Board

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#55]
- [x] Stand up kanban board using agile tool

**Comment by maneyb1** [comment]
- [ ] get current teams' work exposed and visible into the backlog
- [ ] Break IHP IPT concepts into features


- 

- [ ]

**Comment by jamesmrollins** [comment]
@maneyb1 @RossSpeir  

I established an ART Program Kanban [here](https://app.zenhub.com/workspaces/art-program-backlog-626704136331650018f62550/board?repos=485524192).  You are both invited as collaborators.

**Comment by maneyb1** [comment]
IHP Work in progress: 
https://dvagov.sharepoint.com/sites/CIDMOPortfolioManagement/_layouts/15/Doc.aspx?OR=teams&action=edit&sourcedoc={EE7915CA-FCF9-4505-AA9C-DF9BC991EA0B}
