### ISSUE TITLE
As a CIDMO COR, I need to understand FY22 contract actions needed to support first increment of work

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#56]

**Comment by maneyb1** [comment]
@aimeebenson - Add FY22 acquisition planning pre-leading SAFe training milestones/schedule to card

**Comment by maneyb1** [comment]
Aimee aligned acquisition schedule with SAFe planning schedule and acquisition POCs are included on candidate list for the April Leading SAFe training so that they have good idea of language to use in their PWS's that will supply resources on the teams for the first and second increment of work

**Comment by maneyb1** [comment]
@aimeebenson 
- [x] introduce training requirements for this team (linked in learning scrum basics or scrum cert prep and key sections of Kanban fundamentals
- [x] update training plan
- [x] share backlog of current and planned IHP increments of work
- [x] Evaluate Participatory budgeting possibilities
~~- [ ] Define how we will decide how much goes where.~~

**Comment by aimeebenson** [comment]
Meeting scheduled with TAS to discuss  Participatory budgeting.  Website reviewed.

**Comment by maneyb1** [comment]
@maneyb1 
- [x] see if there is a KANBAN training in LIL that is comparable to the TMS module
