### ISSUE TITLE
Gather and Curate FAQ Content

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#57]
- [x] Gather emerging questions
- [x] Curate a FAQ database (SharePoint?)
- [x] Develop questions
- [x] Elicit Responses from content SMEs

**Comment by brandymorrison** [comment]
FAQs have been developed. Some still need responses. We are also awaiting a response from Aldo from the questions his team had to ensure that those are captured here as well.

**Comment by brandymorrison** [comment]
I have added FAQs by category to the wiki associated with the teams channel

**Comment by maneyb1** [comment]
@brandymorrison - I recommend asking @weaverjj  to review and provide input
