### ISSUE TITLE
Identify JIRA license source, set up LCMT

### ISSUE THREAD

**Issue by jamesmrollins** [jamesmrollins/CIDMO_LCMT#64]
- [x] Contact OIT and see if we can align with their license.
- [ ] Set up LCMT Members and train.

**Comment by maneyb1** [comment]
@RossSpeir 
- [ ] Contact DOTS team
[https://vajira.max.gov/servicedesk/customer/portal/1](url)

**Comment by maneyb1** [comment]
@jamesmrollins In meantime, can we set up a board in Zenhub to start building IHP program Kanban?

**Comment by jamesmrollins** [comment]
Have developed the ZENHUB export action. Will test import to JIRA by 4/12.

**Comment by jamesmrollins** [comment]
FYI @RossSpeir @maneyb1 @aimeebenson 

1.  Navigated to the max.gov VA-DOTS page and put in a request for a Jira instance.
2.  I also requested a "discovery" meeting to discuss setting up the organization and how we go about doing that.
3. Hopefully more to report tomorrow.

**Comment by jamesmrollins** [comment]
Going to split this card into two others for procure license and set up LCMT.
