### ISSUE TITLE
As a CIMDO PM, I need the MS use memo to be approved by Chuck Hume

### ISSUE THREAD

**Issue by aimeebenson** [jamesmrollins/CIDMO_LCMT#69]
- [x] Finish Writing SOP

- [x] Finish Writing Pipeline Template

- [x] Tommy Barnes review

- [x] Send to mail call for Chuck review.

**Comment by jamesmrollins** [comment]
SOP is written and sent to Tommy and JN for review.

**Comment by aimeebenson** [comment]
Follow up with Tommy today.  He said he'd get to the review by tomorrow.  Chuck H review will have to happen next week.  Waa Waa Waaahhh
