### ISSUE TITLE
User Story:  User needs training support materials and in-person training that support understanding Lean-Agile Product Development

### ISSUE THREAD

**Issue by jamesmrollins** [jamesmrollins/CIDMO_LCMT#7]
# Understand Lean-Agile Development

Develop training materials that support the development of the competencies below:

- Understand and relate lean-agile terms, acronyms and principles.
- Understand value streams and how development value streams support clinical value streams.
- Understand the role of the Agile Release Train and how they fulfill product and service requests.
- Understand how product portfolios are prioritized by the IHPMB and sent to Agile Release Trains for development.
- Understand how the organization will use cadence to enhance flow, planning and task execution.

## Teaching Methods

- Provide GitHub repository template with Standing Operating Procedures and Lean-Agile guides with links to videos and support materials.
- In-person training for Agile Teams via CIO contracts.
- In-person coaching.

**Comment by maneyb1** [comment]
Suggest we have Brandy read as well

- [x] Get Brandy trained on using GitHub
