### ISSUE TITLE
Prepare Transformation Plan Dissemination

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#70]
- [x] Collect and harmonize feedback from leadership team and PMs
- [x] Identify where and when to disseminate transformation plan

**Comment by maneyb1** [comment]
This document can be a communication tool with partners. 
@maneyb1 - deliver transformation plan to Felise and Chuck Hume as part of Ops and SES plan updates

**Comment by jamesmrollins** [comment]
Disseminate List:

Kellie disseminate under JN email?
- [x] CIDMO Distribution Group
- [x] OHI Distribution Group
~~- [ ] Portfolio Manager, DevSecOps~~
- [x] Members of the IHPMB?
- [x] Share with Sheila

**Comment by maneyb1** [comment]
Messaged on All Staff Call. 
@brandymorrison - add transformation plan to Friday Five

**Comment by brandymorrison** [comment]
@maneyb1 Did you share with Sheila?

**Comment by RossSpeir** [comment]
I will share with Darren Wilson
