### ISSUE TITLE
As the OIT CPRS team (and CIDMO Partner), I need to understand my teams potential roles in this ART

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#72]
- [x] Review ART design with OIT stakeholders
- [x]  get input and discuss implications of this on OIT 
- [x] Identify if any of the OIT partners want to attend the 5/10 Training by 4/15

**Comment by maneyb1** [comment]
Jolie took a new position, need to introduce ourselves to new team
@aimeebenson - scheduled meeting with Tommy for the 15th

@RossSpeir - please send invite for Monday 11EDT to review IHP ART Design with OIT CPRS team and Kate, and hopefully Jonathan. 
@jamesmrollins  - confirm with Ross that you can make that time - you will need to drive the review of the map. 

CPRS Team includes: 
kathryn.cillessen@va.gov
James.Rollins1@va.gov 
Ross.Speir2@va.gov
Jason.Hawsey2@va.gov
Tamara.Diltz-Andary@va.gov
Elizabeth.Griffith2@va.gov
Alan.Montgomery@va.gov
Jonathan.Nebeker@va.gov and Jonathan.nebeker@hsc.utah.edu

**Comment by maneyb1** [comment]
Per Ross,  Kate has requested we postpone this OIT discussion until AFTER next weeks' SAFe training.  I think she's right - the discussion with OIT will be more fruitful when Kate has a better understanding of the new process she oversees.

**Comment by maneyb1** [comment]
@RossSpeir - I think delaying input from OIT on the ART is risky - will consult with Jonathan on level of risk and how we wants to address.

**Comment by maneyb1** [comment]
@jamesmrollins - we should discuss the IHPMB/ICC briefing with Kate on Monday.

**Comment by RossSpeir** [comment]
4/18 call will be kept high level. 
Action Item: How does the 'IHP process' need to change for national reminders (and other smaller-level efforts)? This is related to the ART Canvas and Roadmap (#79).
Action Item: We'll need a follow on with Kate to nail down decisions / plans regarding incorporating national reminders work into the IHP process.

**Comment by jamesmrollins** [comment]
Invite Elizabeth Griffiths to meeting with Kate Cillessen on Monday.  @maneyb1 will confirm meeting.

@maneyb1 and @jamesmrollins will meet with JN during Tuesday weekly to set up a more formal meeting with OHI/OIT.
