### ISSUE TITLE
As the RTE, I need teams to begin populating the Program KANBAN Board

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#73]
- [x] Establish regular planning meetings with RTE
- [x] Identify business analysis team candidates
- [x] Communicate standard definition of epics, capabilities, features, user stories with examples
- [x] Break 1 IHP IPT concept into Epics, themes, user stories and/or features
- [x] Create a product roadmap that communicates how existing approved IHP work is going to translate into prioritized future work.

**Comment by maneyb1** [comment]
I started a Program Board in planner to help conceptualize how we will map existing work into IHP ART
https://tasks.office.com/DVAGOV.onmicrosoft.com/en-US/Home/Planner#/plantaskboard?groupId=53b634be-af61-4d94-80d4-14432d2fb546&planId=bIotwlAhBEOP1gd75XDSHIIADEkr

We also need a roadmap - started one in power point but if we get an agile tool up and running we can hopefully use that: https://dvagov.sharepoint.com/sites/CopyofMPKanban/_layouts/15/Doc.aspx?OR=teams&action=edit&sourcedoc={1F2CAF6F-E1FB-4D10-B6C9-7CAE1D05E345}

**Comment by maneyb1** [comment]
@RossSpeir - Can HFE start the business analysis work, starting with the IHP project charters

**Comment by RossSpeir** [comment]
The 'Intake and Discovery' team needs to specify the their objectives using this template: https://teams.microsoft.com/l/file/1F2CAF6F-E1FB-4D10-B6C9-7CAE1D05E345?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&fileType=pptx&objectUrl=https%3A%2F%2Fdvagov.sharepoint.com%2Fsites%2FCopyofMPKanban%2FShared%20Documents%2FIHP%20ART%20Organization%2FAgile%20Team%20Charters.pptx&baseUrl=https%3A%2F%2Fdvagov.sharepoint.com%2Fsites%2FCopyofMPKanban&serviceName=teams&threadId=19:a7a9966579744ca89b9a4faf665039e9@thread.tacv2&groupId=1967f60a-845a-474c-874a-0fd433acaae7

**Comment by maneyb1** [comment]
- [ ] Need to identify CDS backlog
