### ISSUE TITLE
Get 2nd cohort of trainees registered

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#77]
- [ ] ~~Identify business owners to participate in Leading SAFe and SAFe for Teams~~
- [x] Determine strategy for getting CPRS team trained enough to participate in PI planning
- [x] Identify other CIDMO staff who are good candidates for ART roles and recruit for next training
- [x] Message directors to fill remaining slots
- [x] Coordinate payment for 5/5

**Comment by jamesmrollins** [comment]
@maneyb1 will send out a message today for everyone to get their SF182 submitted for next round of training.

**Comment by brandymorrison** [comment]
Awaiting the completion of 182's. Still pending.
