### ISSUE TITLE
Develop Agile Team Charter Strategy

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#78]
- [x] Work with 'FIRM' to identify strategy for chartering the agile teams
- [x] Develop recruitment campaign for new positions

**Comment by maneyb1** [comment]
@maneyb1 - prepare presentation to FIRM on Team Structure and size, negotiate timeframe for filling gov roles, ask how we can support them in filling the roles. Message is pri 1.  who is best fit for team, pri2. clear the right person for the job plate Pri3. discuss training and other needs to make person successful. 
@RossSpeir - show draft charter for business analysis team. Discuss timeline for completing team charters. How can LCMT help facilitate defining the agile team charters? 
- [ ] take IHPMB charter and IPT charter roles and map them to ART

**Comment by RossSpeir** [comment]
[https://app.zenhub.com/files/454514222/d318a546-1f54-4951-bdbe-7b5a037b7752/download](https://app.zenhub.com/files/454514222/d318a546-1f54-4951-bdbe-7b5a037b7752/download)

@jamesmrollins - Could you provide an example for the Working Agreements section?  Also, feedback on the Charter is welcome.

**Comment by maneyb1** [comment]
Started the recruitment campaign for scrum masters and product managers through Directors and all staff channels

**Comment by RossSpeir** [comment]
Link to the BAT charter (notes, assumptions, questions):  https://dvagov.sharepoint.com/:p:/r/sites/CopyofMPKanban/Shared%20Documents/IHP%20ART%20Organization/Business%20Analysis%20Team/Business%20Analysis%20Team%20Charter_v.2.pptx?d=wff3981a3faf14130af4720b4fc3a1833&csf=1&web=1&e=lTfd1K

**Comment by RossSpeir** [comment]
I've worked on applying the ART roles to the Cystatin C effort. 
Due to other CIDMO priorities, we've postponed the 'ART roles for IHPs' meeting to Friday.

**Comment by maneyb1** [comment]
Resource Plan Power Point: https://dvagov.sharepoint.com/:p:/r/sites/CopyofMPKanban/Shared%20Documents/IHP%20ART%20Organization/CIDMO%20Lean-%20Agile%20Resource%20Plan.pptx?d=w1f2caf6fe1fb4d10b6c97cae1d05e345&csf=1&web=1&e=iht2bK
