### ISSUE TITLE
Complete an IHP ART Canvas 

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#79]
- [x] Fill out a ART Charter and Canvas

**Comment by maneyb1** [comment]
@jamesmrollins - send draft IHP Canvas to Kellie for comms review

**Comment by jamesmrollins** [comment]
Each division will provide us with 5 projects to populate the populate the roadmap. Should be complete by 4/22.  Send out a follow-up email on Monday, 4/25. 

- Provide an announcement during the "Friday 5" email to advertise the Scrum Master positions available and provide a link to the position table in SharePoint. Target 4/22 release and pair with Transformation Plan. Talk to your supervisor and then reach out to LCMT.
- Continue to advertise in the All Staff Meeting.
