### ISSUE TITLE
PI Planning Annex/Appendix to Transformation Plan

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#80]
- [x] Begin messaging timeline for PI planning
- [x] Set up Team in MS teams and add dates to Calendar

**Comment by maneyb1** [comment]
Ross and James meeting Friday to review original plan Ross developed. Include Tas. 
Review the training schedule - we need to decide if we want to do SAFe for Teams and PI planning over 4 days/same week or if we want to do back-to-back weeks.

**Comment by jamesmrollins** [comment]
@RossSpeir and @maneyb1 The plan is available in draft.  I also set up an ART Kanban Board.
