### ISSUE TITLE
Review OIT Product Line Playbook for adoption 

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#83]
https://dvagov.sharepoint.com/sites/OITACOEPortal/Methodology/Key%20Changes/Forms/AllItems.aspx?id=/sites/OITACOEPortal/Methodology/Key%20Changes/DevSecOps%20PLM%20L2%20Playbook_Final%20_042721%20-%20signed.pdf&parent=/sites/OITACOEPortal/Methodology/Key%20Changes

**Comment by jamesmrollins** [comment]
@maneyb1 @aimeebenson @RossSpeir @brandymorrison 

# Summary

1. The LCMT transformation plan is consistent with the Product Line Management Playbook. We should continue our scheduled activities and look for opportunities to identify OIT product lines that we would support (i,e., Cerner).

2. The playbook is a  4 step maturity plan that moves OIT from a project to a product focus. 

- **You build it, you own it.**
- **One team, one heartbeat.**
- **Safety is no accident.**
- **Excellence is not a destination its a journey**

## PLM Maturity Level 1 - The plays

- Product mapping
- The "Big Six" which is the core leadership for a product line (PL Mgr, Solution Arch, IT Prod Mgr, IT Ops mgr, Business Owner and Account Mgr.)
- Functional Org chart (like the ART - not the same as HR Org chart)
- Customer messaging (like our Cultural Transformation Plan)
- Business metrics - yup they want to measure outcomes, but they do not define what those are.
- Common Backlog Toolset - They want to use a common tool set like Jira, but don't specifically identify which they will use.  The document is a year old, so likely will be Jira in my estimation.
- Acquisition Mapping - This is similar to the project mapping we are performing to reconcile existing IPT work into the IHP backlog.  They also provide instructions for using unobligated funds.
- Budget Mapping - once the backlog is built, they want to budget according to needs of the portfolio.
- Product Coordination and Planning - They want to run quarterly plans (sounds like a PI), with sprint cycles and and cadence.  They plan to manage the plan using a product backlog tool (again unidentified). They are promoting the concept of "you build it, you own it." This promotes cross-functional teams and minimizes handoffs.  This seems consistent with our Agile approach.
- Establish a Agile Center of Excellence (ACOE) to support implementation.

## Maturity Roadmap

![image.png](https://images.zenhubusercontent.com/5e4eac12455ade27f3584cea/8836f313-e3a0-40ac-9acd-5fc414ea7462)

## PLM Maturity Level 2

- Develop a business value proposition and metric (like our methodological plan)
  - Product measures that are based on _business outcome value._
  -Strategic business results in terms of action, time or burden reduction in clinical (sic) activities.
  - Customer satisfaction in terms of technology functionality and usability.  However, this is **not** a business metric.
  - Measures should be automated (see methodological plan).
   - They provide a reference business scorecard on Teams. 
- Develop a Product Line and Product Outcome Roadmap.
  - Product managers are responsible for a Product Outcome Roadmap that describes the long view of how the product portfolio will support business objectives.
  - The roadmap is updated at each quarterly meeting.
 - Implement DEVSECOPS capabilities applications monitoring.
- Integrate matrixed resources into product teams.  A product team is a cross-functional team that contain the skills and tools that allow them to build, deploy, monitor and operate ta product from birth to death.
- Capture scorecard metrics. These metrics focus on quality, platform downtime reduction, increasing automated testing and related DEVSECOPS measures.

## Maturity Levels 3 and 4 are not defined in the current version of the plan.
