### ISSUE TITLE
Establish baseline knowledge/acceptance of change management

### ISSUE THREAD

**Issue by brandymorrison** [jamesmrollins/CIDMO_LCMT#87]

**Comment by brandymorrison** [comment]
- [x] Create a survey for CIDMO employees to take to establish a baseline of acceptance/perception of change management processes 
- [x] Establish a plan to distribute

**Comment by maneyb1** [comment]
Do we want to review this plan with Change Management SMEs in CIDMO?
- Greg Staudenmaier
- Seema Nazeer
- Andrew Wilson (customer change)

**Comment by maneyb1** [comment]
@brandymorrison - identify distribution channel and send out

**Comment by brandymorrison** [comment]
https://forms.office.com/Pages/ResponsePage.aspx?id=Ixtf6a-r7kWCHberJRqzv5KZDl0LliFCkalX9GtWS0VUNURPNkgzT0w5WExDN0FGWUNTRVdGWjZKTC4u

**Comment by maneyb1** [comment]
@brandymorrison  - we should probably put some context around what change we are referring to in the header of the survey.

**Comment by brandymorrison** [comment]
Establish as Spotlight for distribution 05.10.2022.
