### ISSUE TITLE
Transformation Plan Comms Campaign

### ISSUE THREAD

**Issue by maneyb1** [jamesmrollins/CIDMO_LCMT#89]
- [x] Identify channels/tactics to distribute plan
- [x] Identify owner of monitoring feedback
- [x] Define continuous review and update strategy

**Comment by maneyb1** [comment]
@brandymorrison - work with Stacie R on OHI blog?

**Comment by RossSpeir** [comment]
James provided feedback  on the document (looks good).
Brandy will continue working on it.
